# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 02 Feb 2021 14:20:28 +0000
*               @ALL          1
*               @user         8
