<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: voxcity
 * Date: Tue, 02 Feb 2021 19:03:45 +0100
 */

$conf['title'] = 'VoxcityWiki';
$conf['lang'] = 'pt-br';
$conf['sidebar'] = 'Menu';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['plugin']['authpdo']['select-groups'] = '</textare�0a></td></tr><tr class="default"><td class="label"><span class="outkey">plugin»authpdo»insert-user</span><img src="/dokuwiki/lib/plugins/config/images/danger.png" alt="danger" title="Perigo: Alterar esta opção poderá tornar o seu wiki e menu de configuração inacessíveis." /><label for="config___plugin____authpdo____insert-user">Declaração SQL para inserir um novo usuário no banco de dados</label></td><td class="value"><textarea rows="3" cols="40" id="config___plugin____authpdo____insert-user" name="config[plugin____authpdo____insert-user]" class="edit" >';
