# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Tue, 02 Feb 2021 14:20:28 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

voxcity:$2y$10$dRYQjWCdoEKjR06mCjxvROvdVjbr/ehKQZJ4bcFrkEH2fRra81L7m:rafael:rafael.manarin@voxcity.com.br:admin,user
